name: 'Tests'

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: ./build-env.sh src && NODE_OPTIONS="--max-old-space-size=8192" npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage --reporters=mocha,coverage-istanbul
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK }}
